[book]
authors = ["Cerbos"]
language = "en"
multilingual = false
src = "src"
title = "Cerbos Guide"

[output.html]
git-repository-url = "https://github.com/cerbos/tutorial"
theme = "ayu"
default-theme = "ayu"
preferred-dark-theme = "ayu"